# frozen_string_literal: true

module Zoom
  CLIENT_ID = 'XXXXXXXXXXXXXXXXXXXXX'
  REDIRECT_PORT = 8000
  REDIRECT_URI = "http://localhost:#{REDIRECT_PORT}/"
  CLIENT_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
end
